### PR TITLE
Remove Skip-con

### PR DESCRIPTION
**Pull request by JusperLee**
I deleted the skip_con because the result was not good

### CODE REVIEW

**Comment by jvel07** [comment]
Does this mean that the skip connection parameter is not being used as in the paper or?

**Comment by JusperLee** [comment]
This part of the code should have been included in his paper.

**Comment by jvel07** [comment]
Their paper mention they use different values for the skip connection (hid_skip=128 being the best value). Where can I set this value from your repo? Or is it implemented in a different way?

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/master/Conv_TasNet_Pytorch/Conv-TasNet-Skip

**Pull request merged**
